export const icons = {
  apple: require("../assets/icons/apple.png"),
  check: require("../assets/icons/check.png"),
  facebook: require("../assets/icons/facebook.png"),
  google: require("../assets/icons/google.png"),
  xcircle: require("../assets/icons/xcircle.png"),
  slogo: require("../assets/logo/logo.svg"),
  logo: require("../assets/logo/logo.png"),
  coloredHouse: require("../assets/icons/colored_house.png"),
  unColoredHouse: require("../assets/icons/uncolored_house.png"),
  coloredCalender: require("../assets/icons/colored_calendar.png"),
  unColoredCalender: require("../assets/icons/uncolored_calendar.png"),
  faceAnalyze: require("../assets/icons/analyze_icon.png"),
  notification: require("../assets/icons/notification.png"),
};
